# Generated by Django 4.0.3 on 2022-03-02 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_contributor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('tag', models.CharField(choices=[('B', 'bug'), ('E', 'enhancement'), ('T', 'task')], max_length=1)),
                ('priority', models.CharField(choices=[('L', 'low'), ('M', 'medium'), ('H', 'high')], max_length=1)),
                ('status', models.CharField(choices=[('T', 'todo'), ('I', 'in progress'), ('D', 'done')], max_length=1)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to='projects.contributor')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_issues', to='projects.contributor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
