# Generated by Django 4.0.3 on 2022-03-02 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
